@startuml

title __CONSTANTS's Class Diagram__\n

  namespace fi.delektre.ringa.ring_thesis {
    namespace constants {
      class fi.delektre.ringa.ring_thesis.constants.AppConst {
          + ACTION_CONNECT : String
          + ACTION_GATT_CONNECTED : String
          + ACTION_GATT_DATA_AVAILABLE : String
          + ACTION_GATT_DISCONNECTED : String
          + ACTION_GATT_SERVICES_DISCOVERED : String
          + APPLICATION_HOST_SELECTION : String
          + APPLICATION_PREF_CHANGED : String
          + BLE_ERROR_OCCURED : String
          + BLE_MSG_LED_VALUE : String
          + BLE_MSG_MEASURE_TIME : String
          + BLE_MSG_MEASURE_VALUE : String
          + BLE_MSG_STEP_TIME : String
          + BLE_MSG_STEP_VALUE : String
          + CALLBACK_REF : String
          {static} + CLIENT_CHARACTERISTIC_CONFIG : UUID
          {static} + CMD_CHARACTERISTIC : String
          {static} + DATA_CHARACTERISTIC : String
          + DATA_LED_BLUE : String
          + DATA_LED_GREEN : String
          + DATA_LED_NIR : String
          + DATA_LED_ORANGE : String
          + DATA_LED_RED : String
          + DATA_LED_YELLOW : String
          + DATA_STEPS : String
          + DATA_TEMP1 : String
          + DATA_TEMP2 : String
          + EXTRA_DATA : String
          + KEY_BLE_ADDR : String
          + KEY_BLE_CHARACTERISTIC : String
          + KEY_BLE_NAME : String
          + KEY_BLE_SERVICE : String
          + KEY_ENABLE_LOCATION : String
          + KEY_ENABLE_SYNC : String
          + KEY_ERROR : String
          + KEY_ID : String
          + KEY_IS_BOOLEAN : String
          + KEY_LED_STATE : String
          + KEY_MESSENGER : String
          + KEY_MODEL : String
          + KEY_PREF : String
          + KEY_PWM_LED_BLUE : String
          + KEY_PWM_LED_GREEN : String
          + KEY_PWM_LED_NIR : String
          + KEY_PWM_LED_ORANGE : String
          + KEY_PWM_LED_RED : String
          + KEY_PWM_LED_UVA : String
          + KEY_PWM_LED_UVB : String
          + KEY_PWM_LED_YELLOW : String
          + KEY_STATUS : String
          + KEY_TITLE : String
          + KEY_USER_ID : String
          {static} + LED_CHARACTERISTIC : String
          + PERMISSIONS_REQUEST_ACCESS_COARSE_LOCATION : int
          + PKG_CTRL : String
          + PKG_DATA : String
          + PKG_TYPE : String
          + REQUEST_ENABLE_BT : int
          {static} + RING_CMD_CALIBRATE : String
          {static} + RING_CMD_NOP : String
          {static} + RING_CMD_REBOOT : String
          {static} + RING_CMD_RESET : String
          {static} + RING_CMD_SETDATE : String
          {static} + RING_SERVICE : String
          + STATE_CONNECTED : int
          + STATE_CONNECTING : int
          + STATE_DISCONNECTED : int
          + STATE_DISCONNECTING : int
          {static} + UUID_CMD_CHARACTERISTIC : UUID
          {static} + UUID_DATA_CHARACTERISTIC : UUID
          {static} + UUID_LED_CHARACTERISTIC : UUID
          {static} + UUID_RING_SERVICE : UUID
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
